version: "3.3"

services:
 python:
   build: .
   container_name: python
   restart: always
   #ports:
     #- 8080:80
   networks:
     - python_net

 nginx:
   image: nginx
   restart: always
   container_name: nginx
   ports:
    - 80:80
   volumes:
     - ./nginx:/etc/nginx/conf.d
   networks:
     - python_net
networks:
  python_net:  
